CREATE TABLE PRICES(
  BRAND_ID INT,
  START_DATE DATETIME,
  END_DATE DATETIME,
  PRICE_LIST int,
  PRODUCT_ID int,
  PRIORITY int,
  PRICE double,
  CURR VARCHAR(10),
  constraint PK_D primary key (PRODUCT_ID, START_DATE,END_DATE)
);
